/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author Rafael
 */
public class SelectOptions extends javax.swing.JFrame {
    private ActionListener eventListener;

    /**
     * Creates new form SelectOptions
     * @param title
     */
    public SelectOptions(String title) {
        initComponents();
        this.frameTitle.setText(title);
        
        this.xPanel.setVisible(false);
        this.yPanel.setVisible(false);
        this.degreesPanel.setVisible(false);
    }
    
    public void addEventListener(ActionListener actionListener) {
        this.eventListener = actionListener;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameTitle = new javax.swing.JLabel();
        xPanel = new javax.swing.JPanel();
        xSlider = new javax.swing.JSlider();
        xLabel = new javax.swing.JLabel();
        xValueLabel = new javax.swing.JLabel();
        yPanel = new javax.swing.JPanel();
        ySlider = new javax.swing.JSlider();
        yLabel = new javax.swing.JLabel();
        yValueLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        degreesPanel = new javax.swing.JPanel();
        degreesSlider = new javax.swing.JSlider();
        degreesLabel = new javax.swing.JLabel();
        degreesValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameTitle.setText("[TITLE]");

        xPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        xSlider.setPaintLabels(true);
        xSlider.setPaintTicks(true);
        xSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xSliderStateChanged(evt);
            }
        });
        xPanel.add(xSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, -1, -1));

        xLabel.setText("X");
        xPanel.add(xLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        xValueLabel.setText(String.format("%d", this.xSlider.getValue()));
        xPanel.add(xValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 28, -1, -1));

        yPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ySlider.setPaintLabels(true);
        ySlider.setPaintTicks(true);
        ySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ySliderStateChanged(evt);
            }
        });
        yPanel.add(ySlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, -1, -1));

        yLabel.setText("Y");
        yPanel.add(yLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        yValueLabel.setText(String.format("%d", this.ySlider.getValue()));
        yPanel.add(yValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 29, -1, -1));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        degreesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        degreesSlider.setMaximum(359);
        degreesSlider.setMinimum(1);
        degreesSlider.setPaintLabels(true);
        degreesSlider.setPaintTicks(true);
        degreesSlider.setValue(45);
        degreesSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                degreesSliderStateChanged(evt);
            }
        });
        degreesPanel.add(degreesSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, -1, -1));

        degreesLabel.setText("Ângulo de Rotação");
        degreesPanel.add(degreesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        degreesValueLabel.setText(String.format("%d", this.degreesSlider.getValue()));
        degreesPanel.add(degreesValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 29, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(cancelButton)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(frameTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(degreesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(frameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(degreesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.eventListener.actionPerformed(null);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void xSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xSliderStateChanged
        this.xValueLabel.setText(String.format("%d", xSlider.getValue()));
    }//GEN-LAST:event_xSliderStateChanged

    private void ySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ySliderStateChanged
        this.yValueLabel.setText(String.format("%d", ySlider.getValue()));
    }//GEN-LAST:event_ySliderStateChanged

    private void degreesSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_degreesSliderStateChanged
        this.degreesValueLabel.setText(String.format("%d", degreesSlider.getValue()));
    }//GEN-LAST:event_degreesSliderStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel degreesLabel;
    public javax.swing.JPanel degreesPanel;
    public javax.swing.JSlider degreesSlider;
    private javax.swing.JLabel degreesValueLabel;
    private javax.swing.JLabel frameTitle;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel xLabel;
    public javax.swing.JPanel xPanel;
    public javax.swing.JSlider xSlider;
    private javax.swing.JLabel xValueLabel;
    private javax.swing.JLabel yLabel;
    public javax.swing.JPanel yPanel;
    public javax.swing.JSlider ySlider;
    private javax.swing.JLabel yValueLabel;
    // End of variables declaration//GEN-END:variables
}
